---
deployment:
    tasks:
        - export GITPATH=/home/dokabobc/git
        - export DEPLOYPATH=/home/dokabobc/public_html/
        - /bin/cp $GITPATH/index.html $DEPLOYPATH
        - /bin/cp $GITPATH/translations.html $DEPLOYPATH
        - /bin/cp $GITPATH/about.html $DEPLOYPATH
        - /bin/cp -R $GITPATH/css $DEPLOYPATH
        - /bin/cp -R $GITPATH/img $DEPLOYPATH
        - /bin/cp -R $GITPATH/script $DEPLOYPATH